version: '3.8'

services:
  postgresql:
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=test
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  redis-server:
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/opt/redis